export const MEMBERS_FETCH = 'MEMBERS_FETCH'
export const MEMBERS_SUCCESS = 'MEMBERS_SUCCESS'
export const MEMBERS_ERROR = 'MEMBERS_ERROR'

export const CONFERENCES_FETCH = 'CONFERENCES_FETCH'
export const CONFERENCES_SUCCESS = 'CONFERENCES_SUCCESS'
export const CONFERENCES_ERROR = 'CONFERENCES_ERROR'

export const BOARD_FETCH = 'BOARD_FETCH'
export const BOARD_SUCCESS = 'BOARD_SUCCESS'
export const BOARD_ERROR = 'BOARD_ERROR'
